py_library(
    name = "gnn_wrapper",
    srcs = ["gnn_wrapper.py"],
    data = ["@bark_project//python:bark.so"],
    imports = ["../external/bark_project/python/"],
    deps = ["@bark_project//modules/runtime:runtime"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "gnn_actor_network",
    srcs = ["gnn_actor_network.py"],
    data = ["@bark_project//python:bark.so"],
    imports = ["../external/bark_project/python/"],
    deps = [],
    visibility = ["//visibility:public"],
)