py_library(
    name = "demonstrations",
    srcs = ["demonstration_collector.py"],
    deps = [
            "//bark_ml/library_wrappers/lib_fqf_iqn_qrdqn/agent:training_benchmark_database"
    ],
    visibility = ["//visibility:public"],
)

