filegroup(
    name = "generate_expert_trajectories_tests_data",
    srcs = glob(["*.jblb", "expert_trajectories/**", 'interaction_data_set_mock/**', "*.json"]),
    visibility = ["//visibility:public"],
)
