filegroup(
    name = "tf2rl_tests_data",
    srcs = glob(["*.pkl"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "generate_expert_trajectories_tests_data",
    srcs = glob(["expert_trajectories/**", 'interaction_data_set_mock/**']),
    visibility = ["//visibility:public"],
)
