filegroup(
    name = "gail_testdata",
    srcs = glob([
        #"expert_data/",
        #"logs/",
        #"models/",
        "params/*.json",
                ]),
    visibility = ["//visibility:public"],
)