py_library(
    name = "utils",
    srcs = ["utils.py"],
    visibility = ["//visibility:public"],
)


py_library(
    name = "network",
    srcs = ["network.py"],
    visibility = ["//visibility:public"],
)


