py_library(
    name = "spaces",
    srcs = ["spaces.py"],
    visibility = ["//visibility:public"],
)

cc_library(spaces",
  hdrs = [
    "spaces.hpp",
  ],
  deps = [

  ],
  visibility = ["//visibility:public"],
)
