cc_library(
  name = "nn_to_value_converter",
  hdrs = [
    "nn_to_value_converter.hpp",
    "nn_to_value_converter_sequential.hpp",
    "nn_to_value_converter_policy.hpp"
  ],
  linkstatic=False,
  visibility = ["//visibility:public"],
)