py_library(
    name = "agents",
    srcs = glob(["*.py"]),
    data = ["@bark_project//python:bark.so"],
    imports = ["../external/bark_project/python/"],
    deps = [],
    visibility = ["//visibility:public"],
)