py_test(
    name = "load_expert_trajectories_tests",
    srcs = ["load_expert_trajectories_tests.py"],
    imports = [
            "../../external/bark_project/python/"
            ],
    deps = [
            "//bark_ml/library_wrappers/lib_tf2rl:load_expert_trajectories",
            ],
    visibility = ["//visibility:public"],
    size = "small"
)