py_library(
    name = "graph_networks",
    srcs = ["__init__.py",
            "graph_network.py",
            "interaction_wrapper.py",
            "tf2_edge_graph_network.py",
            "edge_conditioned_wrapper.py"],
    data = ["@bark_project//bark/python_wrapper:core.so"],
    imports = ["../external/bark_project/bark/python_wrapper/"],
    deps = [],
    visibility = ["//visibility:public"],
)