py_library(
    name = "runners",
    srcs = ["__init__.py",
            "tfa_runner.py",
            "ppo_runner.py",
            "sac_runner.py"],
    deps = ["//bark_ml/commons:tracer"],
    visibility = ["//visibility:public"],
)