filegroup(
    name = "gail_testfiles",
    srcs = glob([
                "expert_data/*",
                "logs/*",
                "models/*",
                "params/*"
                ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gail_testdirs",
    srcs = [
        "expert_data",
        "logs",
        "models",
        "params"
    ],
    visibility = ["//visibility:public"],
)