filegroup(
    name = "gail_data",
    srcs = glob([
                "expert_data/**",
                "logs/**",
                "models/**",
                "params/**"
                ]),
    visibility = ["//visibility:public"],
)
