py_test(
  name = "test_generate_launch_configuration",
  srcs = ["test_generate_launch_configuration.py"],
  deps = ["//utils/python:generate_launch_configuration"],
  imports = ["../python/"],
  visibility = ["//visibility:public"],
  size = "small",
)