py_test(
  name = "generate_launch_configuration_test",
  srcs = ["generate_launch_configuration_test.py"],
  deps = ["//utils/python:generate_launch_configuration"],
  imports = ["../python/"],
  visibility = ["//visibility:public"],
  size = "small",
)