py_library(
    name = "agents",
    srcs = ["base_agent.py",
            "sac_agent.py",
            "td3_agent.py",
            "ppo_agent.py",
            "tfa_agent.py"],
    visibility = ["//visibility:public"],
)