py_library(
    name = "observers",
    srcs = ["nn_state_observer.py"],
    data = ["@bark_project//python:bark.so"],
    imports = ["../external/bark_project/python/"],
		deps = ["@bark_project//modules/runtime:runtime"],
		visibility = ["//visibility:public"],
)