filegroup(
    name = "data",
    srcs = glob(["*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "data_dirs",
    srcs = glob([
                "expert_trajectories/**",
                "logs/**",
                "models/**",
                "params/**",
                "pretrained_agent/**"
                ]),
    visibility = ["//visibility:public"],
)