filegroup(
    name = "weights",
    srcs = glob(["iqn/*.pt",
                 "iqn/*.pth",
                 "fqf/*.pt",
                 "fqf/*.pth",
                 "qrdqn/*.pt",
                 "qrdqn/*.pth",
                 ]),
    visibility = ["//visibility:public"],
)
