name: CI-DIADEM

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark-ml-diadem:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv -p python3 ./bark_ml/python_wrapper/venv  --system-site-packages
      - name: Entering the virtual python environment..
        run: . ./bark_ml/python_wrapper/venv/bin/activate
      - name: Running bazel tests..
        run: bazel test :diadem_tests
